name: stuwhisson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38933
title: 'Stu Whisson Songwriter & Stuff'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#491718'
    - '#e1e5e8'
    - '#b3b5c1'
    - '#da9260'
    - '#5f4b4d'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
