name: stuwhisson
favicon: null
layout_spectrum: 0.75
typography_spectrum: 0.18463
title: 'Stu Whisson Songwriter & Stuff'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#a5a5a5'
    - '#464646'
    - '#656565'
    - '#020202'
  brandStrength: 0.5292942423839122
  lightness: 0.039748962968587875
  saturation: 0.5475953775458038
  rhythmicContrast: 0
purpose: []
